#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim: set ts=4 sts=4 sw=4 et:
"""
@author: Wu Liang
@authors: 
@date: Jun 4, 2012 8:24:36 PM
@contact: wuliang@maimiaotech.com
@version: 0.0.0
@deprecated:
@license:
@copyright:
"""

from Sku import Sku
from StaffEvalStatById import StaffEvalStatById
from FavoriteItem import FavoriteItem
from EvalDetail import EvalDetail
from LimitDiscountDetail import LimitDiscountDetail
from AddressResult import AddressResult
from PosterPicture import PosterPicture
from Group import Group
from TaohuaCateStat import TaohuaCateStat
from INWordCategory import INWordCategory
from ADGroupCatMatchPage import ADGroupCatMatchPage
from Brand import Brand
from HotelImage import HotelImage
from ProductImg import ProductImg
from RoomImage import RoomImage
from CampaignSchedule import CampaignSchedule
from INWordAnalysis import INWordAnalysis
from LoginLog import LoginLog
from PromotionInShop import PromotionInShop
from ArticleSub import ArticleSub
from Task import Task
from Keyword import Keyword
from SubUserPermission import SubUserPermission
from TaohuaCateProp import TaohuaCateProp
from Shipping import Shipping
from DiscountDetail import DiscountDetail
from Receiver import Receiver
from CreativeRecord import CreativeRecord
from ItemCategory import ItemCategory
from Shop import Shop
from ADGroupCatmatch import ADGroupCatmatch
from CouponDetail import CouponDetail
from Campaign import Campaign
from HotelOrder import HotelOrder
from Coupon import Coupon
from Distributor import Distributor
from Role import Role
from Check import Check
from Area import Area
from CarriageDetail import CarriageDetail
from StreamWeight import StreamWeight
from ItemProp import ItemProp
from INWordBase import INWordBase
from PurchaseOrder import PurchaseOrder
from UserCredit import UserCredit
from Location import Location
from Cooperation import Cooperation
from OnlineTimeById import OnlineTimeById
from PropImg import PropImg
from Picture import Picture
from ADGroup import ADGroup
from PosterGoodsInfo import PosterGoodsInfo
from DeliveryTemplate import DeliveryTemplate
from Permission import Permission
from SubPurchaseOrder import SubPurchaseOrder
from ProductPropImg import ProductPropImg
from KfcSearchResult import KfcSearchResult
from GroupMember import GroupMember
from AreaOption import AreaOption
from INCategoryAnalysis import INCategoryAnalysis
from CampaignArea import CampaignArea
from BasicMember import BasicMember
from RefundRemindTimeout import RefundRemindTimeout
from TaohuaItemCommentResult import TaohuaItemCommentResult
from LogisticsPartner import LogisticsPartner
from PartnerDetail import PartnerDetail
from INCategoryBase import INCategoryBase
from SellerCat import SellerCat
from TaohuaUpdateInfo import TaohuaUpdateInfo
from TransitStepInfo import TransitStepInfo
from LogisticsCompany import LogisticsCompany
from AfterSale import AfterSale
from RecommendWord import RecommendWord
from ADGroupCatMatchForecast import ADGroupCatMatchForecast
from Item import Item
from SubUserInfo import SubUserInfo
from Trade import Trade
from TaohuaCatePropValue import TaohuaCatePropValue
from RankedItem import RankedItem
from UserInfo import UserInfo
from RecommendWordPage import RecommendWordPage
from OrderAmount import OrderAmount
from HuabaoAuctionInfo import HuabaoAuctionInfo
from ReplyStatById import ReplyStatById
from TaohuaSearchItems import TaohuaSearchItems
from TaohuaItem import TaohuaItem
from RuleData import RuleData
from Hotel import Hotel
from INCategoryChildTop import INCategoryChildTop
from Promotion import Promotion
from Meal import Meal
from Activity import Activity
from Creative import Creative
from Evaluation import Evaluation
from ArticleUserSubscribe import ArticleUserSubscribe
from ArticleBizOrder import ArticleBizOrder
from RoomType import RoomType
from FenxiaoSku import FenxiaoSku
from FavoriteShop import FavoriteShop
from ADGroupPage import ADGroupPage
from StaffEvalStatOnDay import StaffEvalStatOnDay
from Discount import Discount
from Subtask import Subtask
from INCategoryTop import INCategoryTop
from TopFee import TopFee
from ShopCat import ShopCat
from ItemSearch import ItemSearch
from OnlineTimesOnDay import OnlineTimesOnDay
from TradeRate import TradeRate
from User import User
from KeywordForecast import KeywordForecast
from CampaignPlatform import CampaignPlatform
from PromotionInItem import PromotionInItem
from LimitDiscount import LimitDiscount
from TaohuaCategory import TaohuaCategory
from TaohuaDirectory import TaohuaDirectory
from Feature import Feature
from GroupDomain import GroupDomain
from ReplyStatOnDay import ReplyStatOnDay
from INCategoryProperties import INCategoryProperties
from Refund import Refund
from ReferenceDetail import ReferenceDetail
from ChannelOption import ChannelOption
from GradePromotion import GradePromotion
from SellerAuthorize import SellerAuthorize
from TaohuaOrders import TaohuaOrders
from PromotionDisplayTop import PromotionDisplayTop
from Video import Video
from PicUrl import PicUrl
from FenxiaoGrade import FenxiaoGrade
from FenxiaoProduct import FenxiaoProduct
from TradeAmount import TradeAmount
from ItemCat import ItemCat
from ItemImg import ItemImg
from ItemTemplate import ItemTemplate
from TaohuaOrder import TaohuaOrder
from RefundMessage import RefundMessage
from OrderGuest import OrderGuest
from PictureCategory import PictureCategory
from Product import Product
from KeywordQscore import KeywordQscore
from Poster import Poster
from TaohuaItemComment import TaohuaItemComment
from WaitingTimeById import WaitingTimeById
from PromotionDetail import PromotionDetail
from ServiceOrder import ServiceOrder
from HuabaoChannel import HuabaoChannel
from WaitingTimesOnDay import WaitingTimesOnDay
from Room import Room
from FenxiaoItemRecord import FenxiaoItemRecord
from ProductCat import ProductCat
from PropValue import PropValue
from CampaignBudget import CampaignBudget
from Huabao import Huabao
from CrmMember import CrmMember
from Order import Order
from HuabaoPicture import HuabaoPicture
from NonReplyStatOnDay import NonReplyStatOnDay
from LoginUser import LoginUser
from INRecordBase import INRecordBase
from ShopScore import ShopScore
from TradeConfirmFee import TradeConfirmFee
from TaohuaSearchItem import TaohuaSearchItem
from TaohuaRootDirectory import TaohuaRootDirectory
from TaohuaItemPVPair import TaohuaItemPVPair
from PosterChannel import PosterChannel
from NonreplyStatById import NonreplyStatById
from UserTag import UserTag
